# Generated by Django 5.2 on 2025-04-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department'),
        ('visitors', '0002_alter_visitor_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
