# Generated by Django 5.2 on 2025-04-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_department_alter_user_department'),
        ('visitors', '0002_alter_visitor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
