# Generated by Django 5.2 on 2025-04-15 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('visitors', '0004_alter_visitor_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['visit_date'], name='visitors_vi_visit_d_61df01_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['department'], name='visitors_vi_departm_c7cb1b_idx'),
        ),
    ]
