# Generated by Django 5.2 on 2025-04-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('visitors', '0005_visitor_visitors_vi_visit_d_61df01_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
