# Generated by Django 5.2 on 2025-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_visitor_department_alter_visitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
