# Generated by Django 5.2 on 2025-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Brief description of the department', null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the department was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the department was last updated', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
